
apiVersion: v1
kind: Service
metadata:
  name: faceapp-api
spec:
  selector:
    app: faceapp-api
  ports: 
  - protocol: TCP
    port: 3000
    targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: faceapp-api

spec:
  selector:
    matchLabels:
      app: faceapp-api
  replicas: 2
  template:
    metadata:
      labels: 
        app: faceapp-api
    spec:
      containers:
      - name: faceapp-api
        image: masterziii/sca-project-backend:latest
        ports:
        - containerPort: 3000
          
