version: '3.8'

services:

  # Backend api
  api:
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_URI: postgres://postgres:test@postgres:5432/faceapp
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/faceapp-api

  # Postgres dB
  postgres:
    build: ./postgres
    environment:
      # POSTGRES_URI: postgres://postgres:test@postgres:5432/faceapp
      POSTGRES_DB: faceapp
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
