version: '3.8'

services:

  # Backend api
  api:
    build: .
    depends_on:
      - postgres
    # env_file:
    #   - ./.env.test.local
    environment:
      DB_URI: postgres://postgres:test@postgres:5432/faceapp-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      PORT: 3050
      CLARIFAI_API: "a45c52fbb42f4f68892eaa238569902c"
    ports:
      - "3050:3050"
    volumes:
      - .:/usr/src/faceapp-api

  # Postgres dB
  postgres:
    build: ./postgres

    # specify file with environment variables
    # env_file:
    #   - ./.env.test.local
    environment:
      # - DB_URI: "postgres://postgres:test@postgres:5432/faceapp-test"
      POSTGRES_DB: faceapp-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
