version: '3.8'

services:

  # Backend api
  api:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_URI: postgres://postgres:test@postgres:5432/faceapp
      REDIS_URI: redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/faceapp-api

  # Postgres dB
  postgres:
    build: ./postgres
    environment:
      POSTGRES_DB: faceapp
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Redis dB
  redis:
    image: redis
    ports: 
      - "6379:6379"

volumes:
  pgdata: