version: '3.8'

services:

  # Backend api
  api:
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_URI: postgres://postgres:test@postgres:5432/faceapp
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/faceapp-api

  # Postgres dB
  postgres:
    build: ./postgres
    environment:
      POSTGRES_URI: postgres://postgres:test@postgres:5432/faceapp
      POSTGRES_DB: process.env.POSTGRES_DB
      POSTGRES_HOST: process.env.POSTGRES_HOST
      POSTGRES_USER: process.env.POSTGRES_USER
      POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD
    ports:
      - "2345:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
