BEGIN TRANSACTION;

CREATE TABLE users(
    id serial PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    department VARCHAR(50),
    title VARCHAR(50),
    joined TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMIT;